"""Add total_cost column to DocumentLine

Revision ID: daf63bbfc08c
Revises: a6b14969c2a9
Create Date: 2025-11-20 19:41:46.503356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf63bbfc08c'
down_revision = 'a6b14969c2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.alter_column('vat_amount',
           existing_type=sa.VARCHAR(length=5),
           type_=sa.Numeric(precision=12, scale=2),
           existing_nullable=True,
           postgresql_using="NULLIF(vat_amount, '')::numeric(12,2)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_lines', schema=None) as batch_op:
        batch_op.alter_column('vat_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
